export {default as HomePage} from './HomePage'
export {default as SubjectPage} from './SubjectPage'
export {default as AddStudent} from './AddStudent'
export {default as AddSubject} from './AddSubject'
export {default as EditSubject} from './EditSubject'
export {default as EditStudent} from './EditStudent'
export {default as Error404} from './Error404'